# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodbookapp', '0002_auto_20170320_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_recipe', to='foodbookapp.Recipe'),
        ),
    ]
