# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbookapp', '0002_auto_20170303_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
