# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbookapp', '0003_recipe_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pictureLink',
            field=models.URLField(blank=True),
        ),
    ]
