# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodbookapp', '0003_auto_20170320_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tagTitle',
            new_name='title',
        ),
    ]
