# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodbookapp', '0004_recipe_picturelink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='favouritedBy',
        ),
    ]
