# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbookapp', '0005_auto_20170320_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(blank=True, upload_to='recipe_images'),
        ),
    ]
