# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodbookapp', '0006_auto_20170322_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='slug',
        ),
    ]
