# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-05 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbookapp', '0006_remove_recipe_recipeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
