# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 13:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodbookapp', '0007_auto_20170305_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favouritedBy',
            field=models.ManyToManyField(related_name='user_recipe_favourites', to=settings.AUTH_USER_MODEL),
        ),
    ]
