# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbookapp', '0008_recipe_favouritedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
