# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodbookapp', '0006_auto_20170322_1243'),
        ('foodbookapp', '0008_userprofile_slug'),
    ]

    operations = [
    ]
