# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 13:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodbookapp', '0009_auto_20170309_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='submittedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
