# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 14:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbookapp', '0010_recipe_submittedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='favouritedBy',
            field=models.ManyToManyField(blank=True, related_name='user_recipe_favourites', to=settings.AUTH_USER_MODEL),
        ),
    ]
