# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbookapp', '0011_auto_20170309_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='submitDate',
            field=models.DateField(null=True),
        ),
    ]
