# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 15:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodbookapp', '0012_recipe_submitdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='submittedBy',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userProfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
