# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbookapp', '0012_recipe_submitdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipeText',
            field=models.TextField(null=True),
        ),
    ]
