# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodbookapp', '0013_auto_20170309_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='submittedBy',
        ),
    ]
