# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodbookapp', '0014_auto_20170309_2312'),
        ('foodbookapp', '0014_remove_recipe_submittedby'),
    ]

    operations = [
    ]
