# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbookapp', '0016_auto_20170311_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='raters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='score',
            field=models.FloatField(default=0, max_length=1),
        ),
    ]
