# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-15 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbookapp', '0018_auto_20170314_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pictureLink',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='submitDate',
            field=models.DateField(null=True),
        ),
    ]
