# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodbookapp', '0019_auto_20170315_1641'),
        ('foodbookapp', '0019_auto_20170315_1630'),
    ]

    operations = [
    ]
