# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbookapp', '0020_merge_20170315_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='recipe',
        ),
        migrations.AddField(
            model_name='tag',
            name='recipe',
            field=models.ManyToManyField(to='foodbookapp.Recipe'),
        ),
    ]
