# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodbookapp', '0021_auto_20170316_1350'),
        ('foodbookapp', '0020_merge_20170315_2058'),
    ]

    operations = [
    ]
