# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodbookapp', '0022_auto_20170317_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_body',
            new_name='com_body',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commented_on',
            new_name='com_recipe',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commented_by',
            new_name='com_user',
        ),
    ]
