# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbookapp', '0022_remove_recipe_picturelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
