# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbookapp', '0023_userprofile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favourites',
            field=models.IntegerField(default=0),
        ),
    ]
