# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbookapp', '0024_auto_20170317_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='recipe',
            field=models.ManyToManyField(blank=True, related_name='recipe_tags', to='foodbookapp.Recipe'),
        ),
    ]
