# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodbookapp', '0029_auto_20170320_1048'),
        ('foodbookapp', '0021_auto_20170316_1350'),
    ]

    operations = [
    ]
