# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodbookapp', '0026_remove_recipe_submitdate'),
        ('foodbookapp', '0030_merge_20170320_1309'),
    ]

    operations = [
    ]
