# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodbookapp', '0031_merge_20170320_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='raters',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='score',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='recipe',
        ),
    ]
